"""change col Score in detailstranscipt to nullable=True

Revision ID: 0b1d81ace6f3
Revises: dab014f6ee4e
Create Date: 2021-12-01 11:28:50.314373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b1d81ace6f3'
down_revision = 'dab014f6ee4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detailstranscript', 'score', existing_type=sa.Float(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detailstranscript', 'score', existing_type=sa.Float(), nullable=False)
    # ### end Alembic commands ###
