"""add column active to course and semester table

Revision ID: 6e93b8f8c282
Revises: e7269dc56226
Create Date: 2021-11-21 19:40:17.064083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e93b8f8c282'
down_revision = 'e7269dc56226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semester',
        sa.Column('active', sa.Boolean(), nullable=False)
    )
    op.add_column('course',
        sa.Column('active', sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semester','active')
    op.drop_column('course','active')

    # ### end Alembic commands ###
