"""add column status to resume table

Revision ID: a817979962d0
Revises: d7c3cb0f052d
Create Date: 2021-12-06 19:14:10.712030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a817979962d0'
down_revision = 'd7c3cb0f052d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'status')
    # ### end Alembic commands ###
