"""add confirm column to resume table

Revision ID: bdde44a96627
Revises: 1c114b2ce556
Create Date: 2021-12-05 23:11:54.749656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdde44a96627'
down_revision = '1c114b2ce556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('resume', sa.Column('confirm', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'confirm')
    
    # ### end Alembic commands ###
