"""add column to store public-id image when upload to cloudinary

Revision ID: dab014f6ee4e
Revises: 6e93b8f8c282
Create Date: 2021-11-27 19:02:56.377197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dab014f6ee4e'
down_revision = '6e93b8f8c282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user',
        sa.Column('image_id', sa.String(length=200), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_id')
    # ### end Alembic commands ###
