"""add column modified_at to detailstranscript table

Revision ID: e7269dc56226
Revises: 205e86bb940f
Create Date: 2021-11-21 18:56:02.140281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7269dc56226'
down_revision = '205e86bb940f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detailsTranscript',
        sa.Column('modified_at', sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.drop_column('detailsTranscript','modified_at')
    # ### end Alembic commands ###
